name: Black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: rodrigogiraoserrao/python-black-check@master
      with:
        line-length: '80'
        path: '.'
        include: 'apps'
        exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)'