name: Code-checker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Gathering the changed files
      run: |
        git fetch origin
        files=$(git diff --name-only origin/main -- "*.py")
        echo "$files"
        echo "$files" > changed_files.txt
    - name: Analysing the code with pylint
      run: |
        if [ -s changed_files.txt ]; then
            files=$(cat changed_files.txt)
            pylint \
                --disable duplicate-code \
                --ignore=$(paste -sd, - < .pylint_ignore) $files
        else
            echo "No changed files to PyLint-check"
        fi
    - name: Analysing the code style with black
      run: |
        if [ -s changed_files.txt ]; then
            files=$(cat changed_files.txt)
            black --check --diff $files
        else
            echo "No changed files to Black-check"
        fi